#!/usr/bin/env python3
"""
VS Code Artifacts Example - Shows how to display rich content in VS Code.

Prerequisites:
    1. Install VS Code extension: cd vscode-extension && npm install && npm run compile
    2. Run extension in debug mode (F5 in VS Code)
    3. Install websocket client: pip install websocket-client

Usage:
    python 04_vscode_artifacts.py
"""
from prettycli import vscode


def demo_chart():
    """Show a bar chart in VS Code."""
    print("Showing bar chart...")
    vscode.show_chart(
        chart_type="bar",
        labels=["Q1", "Q2", "Q3", "Q4"],
        datasets=[
            {"label": "2023", "data": [100, 150, 120, 180]},
            {"label": "2024", "data": [120, 180, 160, 220]},
        ],
        title="Quarterly Sales"
    )


def demo_line_chart():
    """Show a line chart in VS Code."""
    print("Showing line chart...")
    vscode.show_chart(
        chart_type="line",
        labels=["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
        datasets=[
            {"label": "Users", "data": [100, 120, 150, 180, 220, 280]},
        ],
        title="User Growth"
    )


def demo_pie_chart():
    """Show a pie chart in VS Code."""
    print("Showing pie chart...")
    vscode.show_chart(
        chart_type="pie",
        labels=["Desktop", "Mobile", "Tablet"],
        datasets=[
            {"label": "Traffic", "data": [55, 35, 10]},
        ],
        title="Traffic by Device"
    )


def demo_table():
    """Show a table in VS Code."""
    print("Showing table...")
    vscode.show_table(
        columns=["ID", "Name", "Email", "Status"],
        rows=[
            [1, "Alice", "alice@example.com", "Active"],
            [2, "Bob", "bob@example.com", "Active"],
            [3, "Charlie", "charlie@example.com", "Inactive"],
        ],
        title="User List"
    )


def demo_json():
    """Show JSON data in VS Code."""
    print("Showing JSON...")
    vscode.show_json({
        "name": "prettycli",
        "version": "0.1.0",
        "features": ["cli", "ui", "vscode"],
        "config": {
            "port": 19960,
            "debug": False
        }
    }, title="Package Info")


def demo_diff():
    """Show a diff in VS Code."""
    print("Showing diff...")
    original = """def hello():
    print("Hello")
    return None"""

    modified = """def hello(name="World"):
    print(f"Hello, {name}!")
    return True"""

    vscode.show_diff(
        original=original,
        modified=modified,
        original_path="hello_v1.py",
        modified_path="hello_v2.py"
    )


def demo_markdown():
    """Show markdown in VS Code."""
    print("Showing markdown...")
    vscode.show_markdown("""
# Report Summary

## Overview
This is a **sample report** generated by *prettycli*.

## Key Metrics
- Users: 1,234
- Sessions: 5,678
- Conversion: 12.5%

## Code Example
```python
from prettycli import vscode
vscode.show_markdown("# Hello")
```

## Conclusion
Everything looks good!
""", title="Report")


def demo_open_file():
    """Open a file with system default application."""
    print("\nTo open files with system default app:")
    print("  vscode.show_excel('/path/to/file.xlsx')  # Open Excel")
    print("  vscode.open_file('/path/to/document.pdf')  # Open any file")


def check_connection():
    """Check VS Code connection status."""
    label, status = vscode.get_status()
    print(f"{label}: {status}")
    return status == "已连接"


if __name__ == "__main__":
    print("VS Code Artifacts Demo")
    print("=" * 40)

    if not check_connection():
        print("\nVS Code extension not connected.")
        print("Please start the extension in VS Code (F5) first.")
        print("Then run this script again.")
        exit(1)

    print()

    try:
        demo_chart()
        demo_line_chart()
        demo_pie_chart()
        demo_table()
        demo_json()
        demo_diff()
        demo_markdown()
        demo_open_file()

        print()
        print("All artifacts displayed!")

        # Show current artifact path
        client = vscode.get_client()
        if client.current_file:
            print(f"Last artifact: {client.current_file}")
        if client.session_path:
            print(f"Session folder: {client.session_path}")

    except ConnectionError as e:
        print(f"Connection error: {e}")
    except Exception as e:
        print(f"Error: {e}")
